print("what do you get when you cross a snowman with a vampire")
input()
print("Frostbite!")
print()
print("What do dentists call a astronaut's cavity?")
input()
print("A Black hole!")
print()
print("Knock Knock.")
input()
print("Who's there?")
input()
print("interrupt cow.")
input()
print("Interrupting cow wh", end='')
print("-MOD!")